import type {
  Open5eSpell,
  Open5eMonster,
  Open5eMagicItem,
} from "@/types/dnd5e";
import { existsSync, readFileSync } from "fs";
import { join } from "path";

// ── Local cache (generated by: npm run fetch-data) ──

const DATA_DIR = join(process.cwd(), "data", "open5e");

function loadJSON<T>(filename: string): T[] {
  const path = join(DATA_DIR, filename);
  if (!existsSync(path)) {
    console.warn(`[open5e] Cache not found: ${path}. Run "npm run fetch-data" to download.`);
    return [];
  }
  return JSON.parse(readFileSync(path, "utf-8"));
}

let _spells: Open5eSpell[] | null = null;
let _monsters: Open5eMonster[] | null = null;
let _items: Open5eMagicItem[] | null = null;

function getSpellsCache(): Open5eSpell[] {
  if (!_spells) _spells = loadJSON<Open5eSpell>("spells.json");
  return _spells;
}

function getMonstersCache(): Open5eMonster[] {
  if (!_monsters) _monsters = loadJSON<Open5eMonster>("monsters.json");
  return _monsters;
}

function getItemsCache(): Open5eMagicItem[] {
  if (!_items) _items = loadJSON<Open5eMagicItem>("items.json");
  return _items;
}

// ── Public API (sync, reads from local cache) ──

export function getSpells(): Open5eSpell[] {
  return getSpellsCache();
}

export function getSpellBySlug(slug: string): Open5eSpell | null {
  return getSpellsCache().find((s) => s.slug === slug) ?? null;
}

export function getMonsters(): Open5eMonster[] {
  return getMonstersCache();
}

export function getMonsterBySlug(slug: string): Open5eMonster | null {
  return getMonstersCache().find((m) => m.slug === slug) ?? null;
}

export function getMagicItems(): Open5eMagicItem[] {
  return getItemsCache();
}

export function getMagicItemBySlug(slug: string): Open5eMagicItem | null {
  return getItemsCache().find((i) => i.slug === slug) ?? null;
}

// ── Legacy async wrappers (backward compat) ──

export async function fetchSpells(): Promise<Open5eSpell[]> {
  return getSpells();
}

export async function fetchSpellBySlug(slug: string): Promise<Open5eSpell | null> {
  return getSpellBySlug(slug);
}

export async function fetchMonsters(): Promise<Open5eMonster[]> {
  return getMonsters();
}

export async function fetchMonsterBySlug(slug: string): Promise<Open5eMonster | null> {
  return getMonsterBySlug(slug);
}

export async function fetchMagicItems(): Promise<Open5eMagicItem[]> {
  return getMagicItems();
}

export async function fetchMagicItemBySlug(slug: string): Promise<Open5eMagicItem | null> {
  return getMagicItemBySlug(slug);
}
