import type {
  Open5eSpell,
  Open5eMonster,
  Open5eMagicItem,
} from "@/types/dnd5e";
import type { Locale } from "@/lib/i18n/types";
import { existsSync, readFileSync } from "fs";
import { join } from "path";

// ── Local cache (generated by: npm run fetch-data) ──

const DATA_DIR = join(process.cwd(), "data", "open5e");

const LOCALE_SUFFIX: Record<Locale, string> = {
  "pt-BR": "-pt",
  en: "",
  es: "-es",
};

// Per-locale cache keyed by "<baseName><suffix>"
const _cache: Record<string, unknown[]> = {};

function loadJSON<T>(filename: string, locale: Locale = "en"): T[] {
  const suffix = LOCALE_SUFFIX[locale];
  const baseName = filename.replace(".json", "");
  const key = `${baseName}${suffix}`;

  if (_cache[key]) return _cache[key] as T[];

  // Try locale-specific file first, fallback to base English file
  if (suffix) {
    const localePath = join(DATA_DIR, `${baseName}${suffix}.json`);
    if (existsSync(localePath)) {
      const data = JSON.parse(readFileSync(localePath, "utf-8")) as T[];
      _cache[key] = data;
      return data;
    }
  }

  const path = join(DATA_DIR, filename);
  if (!existsSync(path)) {
    console.warn(`[open5e] Data file not found: ${path}`);
    return [];
  }
  const data = JSON.parse(readFileSync(path, "utf-8")) as T[];
  _cache[key] = data;
  return data;
}

// ── Public API (sync, reads from local cache) ──

export function getSpells(locale?: Locale): Open5eSpell[] {
  return loadJSON<Open5eSpell>("spells.json", locale);
}

export function getSpellBySlug(
  slug: string,
  locale?: Locale
): Open5eSpell | null {
  return getSpells(locale).find((s) => s.slug === slug) ?? null;
}

export function getMonsters(locale?: Locale): Open5eMonster[] {
  return loadJSON<Open5eMonster>("monsters.json", locale);
}

export function getMonsterBySlug(
  slug: string,
  locale?: Locale
): Open5eMonster | null {
  return getMonsters(locale).find((m) => m.slug === slug) ?? null;
}

export function getMagicItems(locale?: Locale): Open5eMagicItem[] {
  return loadJSON<Open5eMagicItem>("items.json", locale);
}

export function getMagicItemBySlug(
  slug: string,
  locale?: Locale
): Open5eMagicItem | null {
  return getMagicItems(locale).find((i) => i.slug === slug) ?? null;
}

// ── Legacy async wrappers (backward compat) ──

export async function fetchSpells(): Promise<Open5eSpell[]> {
  return getSpells();
}

export async function fetchSpellBySlug(
  slug: string
): Promise<Open5eSpell | null> {
  return getSpellBySlug(slug);
}

export async function fetchMonsters(): Promise<Open5eMonster[]> {
  return getMonsters();
}

export async function fetchMonsterBySlug(
  slug: string
): Promise<Open5eMonster | null> {
  return getMonsterBySlug(slug);
}

export async function fetchMagicItems(): Promise<Open5eMagicItem[]> {
  return getMagicItems();
}

export async function fetchMagicItemBySlug(
  slug: string
): Promise<Open5eMagicItem | null> {
  return getMagicItemBySlug(slug);
}
