export const RANDOM_TABLES: Record<string, string[]> = {
  "Encontro - Floresta": [
    "Um grupo de lobos cerca a estrada, liderados por um lobo atroz",
    "Uma fada brincalhona oferece um trato duvidoso",
    "Arvores caidas bloqueiam o caminho — parece intencional",
    "Um druida solitario pede ajuda para curar uma arvore doente",
    "Bandidos emboscam de cima das arvores",
    "Uma clareira mistica com cogumelos brilhantes",
    "Pegadas enormes levam para dentro da floresta",
    "Um cacador ferido avisa sobre uma criatura nas proximidades",
    "Uma ponte de cordas sobre um desfiladeiro esta prestes a ceder",
    "Elfos da floresta observam o grupo de longe",
    "Um altar antigo coberto de musgo emana magia fraca",
    "Um urso-coruja protege seus filhotes agressivamente",
  ],
  "Encontro - Montanha": [
    "Uma tempestade de neve repentina reduz a visibilidade a zero",
    "Goblins ocuparam uma caverna no caminho",
    "Um gigante de pedra dorme bloqueando a passagem",
    "Desmoronamento de rochas ameaca o grupo",
    "Um eremita oferece abrigo em troca de uma historia",
    "Rastros de dragao sao visiveis nas rochas chamuscadas",
    "Uma ponte de pedra natural sobre um abismo",
    "Anoes mineradores pedem escolta contra monstros",
    "Ventos fortissimos dificultam a escalada",
    "Uma nascente de agua cristalina com propriedades curativas",
  ],
  "Encontro - Cidade": [
    "Um ladrao tenta roubar a bolsa de moedas de um PJ",
    "Um nobre oferece trabalho discreto e bem pago",
    "Uma briga de taverna escala para uma luta de faccoes",
    "Guardas da cidade buscam suspeitos que combinam com a descricao do grupo",
    "Um mercador vende itens magicos duvidosos a precos baixos",
    "Uma crianca perdida pede ajuda para encontrar os pais",
    "Um bardo conta historias sobre um tesouro lendario nas proximidades",
    "Uma guild de ladroes recruta novos membros",
    "Um templo pede voluntarios para uma missao sagrada",
    "Rumores sobre desaparecimentos misteriosos no bairro pobre",
  ],
  "Clima": [
    "Ceu limpo e ensolarado",
    "Nuvens carregadas, chuva iminente",
    "Chuva forte e persistente",
    "Neblina densa reduz visibilidade",
    "Tempestade com raios — perigo ao ar livre",
    "Neve leve cobrindo o chao",
    "Nevasca intensa, quase impossivel viajar",
    "Vento forte dificulta comunicacao e tiro com arco",
    "Calor escaldante — risco de exaustao",
    "Noite estrelada excepcionalmente clara",
  ],
  "Complicacao de Masmorra": [
    "Uma porta esta trancada com uma armadilha de agulhas envenenadas",
    "O chao desaba parcialmente revelando um nivel inferior",
    "Runas brilham nas paredes — um puzzle para abrir a passagem",
    "Agua sobe lentamente na sala",
    "Um espelho magico mostra visoes enganosas",
    "Esporos toxicos enchem o corredor — CON save ou envenenado",
    "Uma sala com gravidade invertida",
    "Portas que se trancam atras do grupo",
    "Ilusao esconde o caminho verdadeiro",
    "Um golem guardiao ativa ao detectar intrusos",
    "Teias de aranha gigantes bloqueiam a passagem",
    "Uma fonte que cura ou envenena — precisa descobrir qual",
    "Inscricoes em idioma antigo contem pista crucial",
    "Mecanismo de engrenagens precisa ser ativado em sequencia",
    "Corredor com laminas pendulares como obstaculo",
  ],
  "Evento Social": [
    "Um festival local esta acontecendo com competicoes e premios",
    "Dois NPCs discutem e pedem ao grupo para mediar",
    "Um convite inesperado para um jantar com pessoa influente",
    "Um velho amigo de um PJ aparece com problemas",
    "Uma acusacao falsa coloca um PJ em risco",
    "Informante oferece segredo valioso por um preco",
    "Tensao politica entre faccoes rivais afeta o grupo",
    "Um artista de rua faz uma profecia criptica sobre o grupo",
    "Leilao de itens raros — oportunidade e rivais",
    "Uma dama em perigo pede socorro — pode ser armadilha",
    "Taverna oferece jogo de apostas com premios magicos",
    "Um mensageiro traz noticias urgentes de terras distantes",
  ],
  "Twist de Plot": [
    "O aliado de confianca tem motivos ocultos",
    "O verdadeiro vilao era alguem que o grupo protegia",
    "O artefato buscado ja foi destruido ha muito tempo",
    "A missao era um teste — o verdadeiro desafio so comeca agora",
    "Um PJ descobre uma conexao pessoal com o antagonista",
    "O mundo que conheciam e uma ilusao ou plano alternativo",
    "O empregador do grupo e na verdade o vilao",
    "Uma profecia se cumpre de forma inesperada",
    "O tesouro esta amaldicoado",
    "Aliados e inimigos trocam de lado simultaneamente",
  ],
};

export function getCategories(): string[] {
  return Object.keys(RANDOM_TABLES);
}

export function rollRandomEvent(category: string): string {
  const table = RANDOM_TABLES[category];
  if (!table || table.length === 0) return "Nenhum evento encontrado";
  return table[Math.floor(Math.random() * table.length)];
}
