#!/usr/bin/env python3
"""
translate-full-es.py
Translates D&D 5e SRD spell descriptions (desc, higher_level, material, range)
from English to Spanish using 500+ pattern rules.
Only processes spells with document__slug == "wotc-srd".
"""

import json
import re
import os

# ---------------------------------------------------------------------------
# Pattern table  (order matters: longer/more specific patterns first)
# Each entry is (regex_pattern, replacement, flags)
# Use named groups where helpful.
# ---------------------------------------------------------------------------

PATTERNS = [
    # =========================================================
    # SENTENCE-LEVEL / OPENING PHRASES
    # =========================================================
    (r"When you cast this spell using a spell slot of (\w+(?:\s+\w+)?) level or higher,",
     r"Cuando lanzas este conjuro usando un espacio de conjuro de nivel \1 o superior,", re.IGNORECASE),
    (r"When you cast this spell using a spell slot of (\w+(?:\s+\w+)?) or higher,",
     r"Cuando lanzas este conjuro usando un espacio de conjuro de \1 o superior,", re.IGNORECASE),
    (r"When you cast this spell at (\w+) level or higher,",
     r"Cuando lanzas este conjuro de nivel \1 o superior,", re.IGNORECASE),
    (r"When you cast this spell using a higher.level spell slot,",
     r"Cuando lanzas este conjuro usando un espacio de conjuro de nivel superior,", re.IGNORECASE),
    (r"When you cast this spell",
     r"Cuando lanzas este conjuro", re.IGNORECASE),
    (r"You cast this spell",
     r"Lanzas este conjuro", re.IGNORECASE),
    (r"If you cast this spell using a spell slot of (\w+(?:\s+\w+)?) level or higher,",
     r"Si lanzas este conjuro usando un espacio de conjuro de nivel \1 o superior,", re.IGNORECASE),
    (r"If you cast this spell using a spell slot of (\w+(?:\s+\w+)?) or higher,",
     r"Si lanzas este conjuro usando un espacio de conjuro de \1 o superior,", re.IGNORECASE),
    (r"You choose one of the following options",
     r"Eliges una de las siguientes opciones", re.IGNORECASE),
    (r"You choose a creature",
     r"Eliges una criatura", re.IGNORECASE),
    (r"You choose",
     r"Eliges", re.IGNORECASE),
    (r"Choose a creature",
     r"Elige una criatura", re.IGNORECASE),
    (r"Choose one creature",
     r"Elige una criatura", re.IGNORECASE),
    (r"Choose up to (\w+) creatures",
     r"Elige hasta \1 criaturas", re.IGNORECASE),
    (r"Choose up to (\w+) willing creatures",
     r"Elige hasta \1 criaturas dispuestas", re.IGNORECASE),
    (r"You create",
     r"Creas", re.IGNORECASE),
    (r"You summon",
     r"Invocas", re.IGNORECASE),
    (r"You call",
     r"Llamas", re.IGNORECASE),
    (r"You touch",
     r"Tocas", re.IGNORECASE),
    (r"You conjure",
     r"Conjuras", re.IGNORECASE),
    (r"You cause",
     r"Provocas", re.IGNORECASE),
    (r"You transform",
     r"Transformas", re.IGNORECASE),
    (r"You teleport",
     r"Te teletransportas", re.IGNORECASE),
    (r"You attempt",
     r"Intentas", re.IGNORECASE),
    (r"You become",
     r"Te vuelves", re.IGNORECASE),
    (r"You gain",
     r"Obtienes", re.IGNORECASE),
    (r"You lose",
     r"Pierdes", re.IGNORECASE),
    (r"You take",
     r"Recibes", re.IGNORECASE),
    (r"You can see",
     r"Puedes ver", re.IGNORECASE),
    (r"You can speak",
     r"Puedes hablar", re.IGNORECASE),
    (r"You can use",
     r"Puedes usar", re.IGNORECASE),
    (r"You can move",
     r"Puedes moverte", re.IGNORECASE),
    (r"You can make",
     r"Puedes hacer", re.IGNORECASE),
    (r"You learn",
     r"Aprendes", re.IGNORECASE),
    (r"You know",
     r"Conoces", re.IGNORECASE),
    (r"You must succeed",
     r"Debes tener éxito", re.IGNORECASE),
    (r"You spend",
     r"Gastas", re.IGNORECASE),
    (r"You roll",
     r"Tiras", re.IGNORECASE),
    (r"You target",
     r"Apuntas a", re.IGNORECASE),
    (r"You ward",
     r"Proteges", re.IGNORECASE),
    (r"You weave",
     r"Tejes", re.IGNORECASE),
    (r"You shape",
     r"Das forma a", re.IGNORECASE),
    (r"You raise",
     r"Levantas", re.IGNORECASE),
    (r"You hurl",
     r"Lanzas", re.IGNORECASE),
    (r"You manifest",
     r"Manifiestas", re.IGNORECASE),
    (r"You point",
     r"Señalas", re.IGNORECASE),
    (r"You speak",
     r"Hablas", re.IGNORECASE),
    (r"You utter",
     r"Pronuncias", re.IGNORECASE),
    (r"You whisper",
     r"Susurras", re.IGNORECASE),
    (r"You reach",
     r"Alcanzas", re.IGNORECASE),
    (r"You exert",
     r"Ejerces", re.IGNORECASE),
    (r"You extend",
     r"Extiendes", re.IGNORECASE),
    (r"You establish",
     r"Estableces", re.IGNORECASE),
    (r"You enter",
     r"Entras en", re.IGNORECASE),
    (r"You expend",
     r"Gastas", re.IGNORECASE),
    (r"You draw",
     r"Extraes", re.IGNORECASE),
    (r"You designate",
     r"Designas", re.IGNORECASE),
    (r"You emit",
     r"Emites", re.IGNORECASE),
    (r"You envelop",
     r"Envuelves", re.IGNORECASE),
    (r"You fill",
     r"Rellenas", re.IGNORECASE),
    (r"You focus",
     r"Te concentras", re.IGNORECASE),
    (r"You force",
     r"Fuerzas", re.IGNORECASE),
    (r"You ignore",
     r"Ignoras", re.IGNORECASE),
    (r"You illuminate",
     r"Iluminas", re.IGNORECASE),
    (r"You implant",
     r"Implantando", re.IGNORECASE),
    (r"You impose",
     r"Impones", re.IGNORECASE),
    (r"You issue",
     r"Emites", re.IGNORECASE),
    (r"You invoke",
     r"Invocas", re.IGNORECASE),
    (r"You place",
     r"Colocas", re.IGNORECASE),
    (r"You project",
     r"Proyectas", re.IGNORECASE),
    (r"You release",
     r"Liberas", re.IGNORECASE),
    (r"You send",
     r"Envías", re.IGNORECASE),
    (r"You set",
     r"Estableces", re.IGNORECASE),
    (r"You shroud",
     r"Envuelves", re.IGNORECASE),
    (r"You signal",
     r"Señalas", re.IGNORECASE),
    (r"You strike",
     r"Golpeas", re.IGNORECASE),
    (r"You suppress",
     r"Suprimes", re.IGNORECASE),
    (r"You sweep",
     r"Barres", re.IGNORECASE),
    (r"You vanish",
     r"Desapareces", re.IGNORECASE),

    # =========================================================
    # SPELL SLOT / LEVEL
    # =========================================================
    (r"a spell slot of (\w+(?:\s+\w+)?) level or higher",
     r"un espacio de conjuro de nivel \1 o superior", re.IGNORECASE),
    (r"a spell slot of (\w+(?:\s+\w+)?) or higher",
     r"un espacio de conjuro de \1 o superior", re.IGNORECASE),
    (r"a spell slot of (\w+(?:\s+\w+)?)",
     r"un espacio de conjuro de \1", re.IGNORECASE),
    (r"spell slots? of (\w+(?:\s+\w+)?) level or higher",
     r"espacios de conjuro de nivel \1 o superior", re.IGNORECASE),
    (r"each slot level above (\w+(?:\s+\w+)?)",
     r"cada nivel de espacio por encima de \1", re.IGNORECASE),
    (r"for each slot level above (\w+(?:\s+\w+)?)",
     r"por cada nivel de espacio por encima de \1", re.IGNORECASE),
    (r"\bspell slots?\b",
     r"espacios de conjuro", re.IGNORECASE),
    (r"\bspell slot\b",
     r"espacio de conjuro", re.IGNORECASE),
    (r"\bhigher.level spell\b",
     r"conjuro de nivel superior", re.IGNORECASE),
    (r"\bcantrips?\b",
     r"truco", re.IGNORECASE),

    # =========================================================
    # SAVING THROWS
    # =========================================================
    (r"must succeed on a (Strength|Constitution|Dexterity|Intelligence|Wisdom|Charisma) saving throw",
     lambda m: f"debe tener éxito en una tirada de salvación de {_ability_es(m.group(1))}", re.IGNORECASE),
    (r"must make a (Strength|Constitution|Dexterity|Intelligence|Wisdom|Charisma) saving throw",
     lambda m: f"debe hacer una tirada de salvación de {_ability_es(m.group(1))}", re.IGNORECASE),
    (r"make a (Strength|Constitution|Dexterity|Intelligence|Wisdom|Charisma) saving throw",
     lambda m: f"hacer una tirada de salvación de {_ability_es(m.group(1))}", re.IGNORECASE),
    (r"(Strength|Constitution|Dexterity|Intelligence|Wisdom|Charisma) saving throw",
     lambda m: f"tirada de salvación de {_ability_es(m.group(1))}", re.IGNORECASE),
    (r"saving throw DC equals? your spell save DC",
     r"CD de tirada de salvación igual a tu CD de salvación de conjuro", re.IGNORECASE),
    (r"saving throw DC",
     r"CD de tirada de salvación", re.IGNORECASE),
    (r"\bsaving throws?\b",
     r"tiradas de salvación", re.IGNORECASE),
    (r"\bsaving throw\b",
     r"tirada de salvación", re.IGNORECASE),
    (r"on a failed save",
     r"en una salvación fallida", re.IGNORECASE),
    (r"on a successful save",
     r"en una salvación exitosa", re.IGNORECASE),
    (r"on a failure",
     r"en un fallo", re.IGNORECASE),
    (r"on a success",
     r"en un éxito", re.IGNORECASE),
    (r"a successful (Strength|Constitution|Dexterity|Intelligence|Wisdom|Charisma) saving throw",
     lambda m: f"una tirada de salvación de {_ability_es(m.group(1))} exitosa", re.IGNORECASE),
    (r"a successful saving throw",
     r"una tirada de salvación exitosa", re.IGNORECASE),
    (r"succeeds on (?:the|its|a) saving throw",
     r"tiene éxito en la tirada de salvación", re.IGNORECASE),
    (r"succeeds on (?:the|its|a) (?:saving throw|save)",
     r"tiene éxito en la tirada de salvación", re.IGNORECASE),
    (r"fails? (?:the|its|a) saving throw",
     r"falla la tirada de salvación", re.IGNORECASE),
    (r"fails? (?:the|its|a) (?:saving throw|save)",
     r"falla la tirada de salvación", re.IGNORECASE),
    (r"halves? (?:the )?damage",
     r"reduce el daño a la mitad", re.IGNORECASE),
    (r"half (?:as much )?damage",
     r"la mitad de daño", re.IGNORECASE),
    (r"half damage",
     r"la mitad del daño", re.IGNORECASE),
    (r"takes? half (?:the )?damage",
     r"recibe la mitad del daño", re.IGNORECASE),
    (r"takes? no damage",
     r"no recibe daño", re.IGNORECASE),
    (r"takes? (\d+d\d+) (\w+) damage",
     r"recibe \1 de daño \2", re.IGNORECASE),

    # =========================================================
    # ABILITY SCORES
    # =========================================================
    (r"\bStrength (?:check|modifier|score|ability)\b",
     r"Fuerza", re.IGNORECASE),
    (r"\bDexterity (?:check|modifier|score|ability)\b",
     r"Destreza", re.IGNORECASE),
    (r"\bConstitution (?:check|modifier|score|ability)\b",
     r"Constitución", re.IGNORECASE),
    (r"\bIntelligence (?:check|modifier|score|ability)\b",
     r"Inteligencia", re.IGNORECASE),
    (r"\bWisdom (?:check|modifier|score|ability)\b",
     r"Sabiduría", re.IGNORECASE),
    (r"\bCharisma (?:check|modifier|score|ability)\b",
     r"Carisma", re.IGNORECASE),
    (r"\bStrength\b",
     r"Fuerza", re.IGNORECASE),
    (r"\bDexterity\b",
     r"Destreza", re.IGNORECASE),
    (r"\bConstitution\b",
     r"Constitución", re.IGNORECASE),
    (r"\bIntelligence\b",
     r"Inteligencia", re.IGNORECASE),
    (r"\bWisdom\b",
     r"Sabiduría", re.IGNORECASE),
    (r"\bCharisma\b",
     r"Carisma", re.IGNORECASE),

    # =========================================================
    # HIT POINTS / ARMOR CLASS
    # =========================================================
    (r"\bhit point maximum\b",
     r"máximo de puntos de golpe", re.IGNORECASE),
    (r"\bhit points?\b",
     r"puntos de golpe", re.IGNORECASE),
    (r"\barmor class\b",
     r"clase de armadura", re.IGNORECASE),
    (r"\btemporary hit points?\b",
     r"puntos de golpe temporales", re.IGNORECASE),
    (r"\btemporary hp\b",
     r"PG temporales", re.IGNORECASE),
    (r"\b(regain|restore)s? (\d+) hit points?\b",
     r"recupera \2 puntos de golpe", re.IGNORECASE),
    (r"\b(regain|restore)s? hit points?\b",
     r"recupera puntos de golpe", re.IGNORECASE),

    # =========================================================
    # DAMAGE TYPES
    # =========================================================
    (r"\bacid damage\b",
     r"daño ácido", re.IGNORECASE),
    (r"\bbludgeoning damage\b",
     r"daño contundente", re.IGNORECASE),
    (r"\bcold damage\b",
     r"daño de frío", re.IGNORECASE),
    (r"\bfire damage\b",
     r"daño de fuego", re.IGNORECASE),
    (r"\bforce damage\b",
     r"daño de fuerza", re.IGNORECASE),
    (r"\blightning damage\b",
     r"daño de rayo", re.IGNORECASE),
    (r"\bnecrotic damage\b",
     r"daño necrótico", re.IGNORECASE),
    (r"\bpierce[d]? damage\b",
     r"daño perforante", re.IGNORECASE),
    (r"\bpiercing damage\b",
     r"daño perforante", re.IGNORECASE),
    (r"\bpoison damage\b",
     r"daño de veneno", re.IGNORECASE),
    (r"\bpsychic damage\b",
     r"daño psíquico", re.IGNORECASE),
    (r"\bradiant damage\b",
     r"daño radiante", re.IGNORECASE),
    (r"\bslashing damage\b",
     r"daño cortante", re.IGNORECASE),
    (r"\bthunder damage\b",
     r"daño de trueno", re.IGNORECASE),
    # standalone types (after the paired forms above)
    (r"\bacid\b",
     r"ácido", re.IGNORECASE),
    (r"\bbludgeoning\b",
     r"contundente", re.IGNORECASE),
    (r"\bcold\b(?=\s+damage|\s+and|\s+or|\s*[,.]|\s*$)",
     r"frío", re.IGNORECASE),
    (r"\bfire\b(?=\s+damage|\s+and|\s+or|\s*[,.]|\s*$)",
     r"fuego", re.IGNORECASE),
    (r"\bforce\b(?=\s+damage|\s+and|\s+or|\s*[,.]|\s*$)",
     r"fuerza", re.IGNORECASE),
    (r"\blightning\b",
     r"rayo", re.IGNORECASE),
    (r"\bnecrotic\b",
     r"necrótico", re.IGNORECASE),
    (r"\bpiercing\b",
     r"perforante", re.IGNORECASE),
    (r"\bpoison(?:ed)?\b(?=\s+damage|\s+condition|\s+and|\s+or|\s*[,.]|\s*$)",
     r"veneno", re.IGNORECASE),
    (r"\bpsychic\b",
     r"psíquico", re.IGNORECASE),
    (r"\bradiant\b",
     r"radiante", re.IGNORECASE),
    (r"\bslashing\b",
     r"cortante", re.IGNORECASE),
    (r"\bthunder\b",
     r"trueno", re.IGNORECASE),

    # =========================================================
    # CONDITIONS
    # =========================================================
    (r"\bblinded\b",
     r"cegado", re.IGNORECASE),
    (r"\bcharmed\b",
     r"hechizado", re.IGNORECASE),
    (r"\bdeafened\b",
     r"ensordecido", re.IGNORECASE),
    (r"\bexhausted\b",
     r"agotado", re.IGNORECASE),
    (r"\bexhaustion\b",
     r"agotamiento", re.IGNORECASE),
    (r"\bfrightened\b",
     r"asustado", re.IGNORECASE),
    (r"\bfright\b",
     r"miedo", re.IGNORECASE),
    (r"\bgrappled\b",
     r"agarrado", re.IGNORECASE),
    (r"\bincapacitated\b",
     r"incapacitado", re.IGNORECASE),
    (r"\binvisible\b",
     r"invisible", re.IGNORECASE),
    (r"\binvisibility\b",
     r"invisibilidad", re.IGNORECASE),
    (r"\bparalyzed\b",
     r"paralizado", re.IGNORECASE),
    (r"\bpetrified\b",
     r"petrificado", re.IGNORECASE),
    (r"\bpoisoned\b",
     r"envenenado", re.IGNORECASE),
    (r"\bprone\b",
     r"tumbado", re.IGNORECASE),
    (r"\brestrained\b",
     r"restringido", re.IGNORECASE),
    (r"\bstunned\b",
     r"aturdido", re.IGNORECASE),
    (r"\bunconscious\b",
     r"inconsciente", re.IGNORECASE),

    # =========================================================
    # ACTIONS / TIMING
    # =========================================================
    (r"\bbonus action\b",
     r"acción adicional", re.IGNORECASE),
    (r"\bas a bonus action\b",
     r"como acción adicional", re.IGNORECASE),
    (r"\breaction\b",
     r"reacción", re.IGNORECASE),
    (r"\bfree action\b",
     r"acción gratuita", re.IGNORECASE),
    (r"\bopportunity attack\b",
     r"ataque de oportunidad", re.IGNORECASE),
    (r"\battack of opportunity\b",
     r"ataque de oportunidad", re.IGNORECASE),
    (r"\bAction Surge\b",
     r"Avalancha de Acciones", re.IGNORECASE),

    # =========================================================
    # CONCENTRATION
    # =========================================================
    (r"\bconcentration\b",
     r"concentración", re.IGNORECASE),
    (r"\brequires concentration\b",
     r"requiere concentración", re.IGNORECASE),
    (r"\bmaintain concentration\b",
     r"mantener concentración", re.IGNORECASE),

    # =========================================================
    # RANGE
    # =========================================================
    (r"\bwithin range\b",
     r"dentro del alcance", re.IGNORECASE),
    (r"\bout of range\b",
     r"fuera del alcance", re.IGNORECASE),
    (r"\blong range\b",
     r"alcance largo", re.IGNORECASE),
    (r"\bshort range\b",
     r"alcance corto", re.IGNORECASE),
    (r"\bnormal range\b",
     r"alcance normal", re.IGNORECASE),
    (r"\bwithin (\d+) feet? of you\b",
     r"a \1 pies de ti", re.IGNORECASE),
    (r"\bwithin (\d+) feet?\b",
     r"en un radio de \1 pies", re.IGNORECASE),
    (r"\bup to (\d+) feet? away\b",
     r"hasta \1 pies de distancia", re.IGNORECASE),
    (r"\b(\d+)[- ]foot radius\b",
     r"radio de \1 pies", re.IGNORECASE),
    (r"\ba (\d+)[- ]foot[- ]radius\b",
     r"un radio de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]radius\b",
     r"radio de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]cube\b",
     r"cubo de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]cone\b",
     r"cono de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]line\b",
     r"línea de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]sphere\b",
     r"esfera de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]cylinder\b",
     r"cilindro de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]square\b",
     r"cuadrado de \1 pies", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]tall\b",
     r"\1 pies de altura", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]wide\b",
     r"\1 pies de ancho", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]long\b",
     r"\1 pies de largo", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]thick\b",
     r"\1 pies de grosor", re.IGNORECASE),
    (r"\b(\d+)[- ]foot[- ]high\b",
     r"\1 pies de alto", re.IGNORECASE),
    (r"\b(\d+) feet? per (\w+)\b",
     r"\1 pies por \2", re.IGNORECASE),
    (r"\b(\d+) feet? per second\b",
     r"\1 pies por segundo", re.IGNORECASE),
    (r"\b(\d+) feet?\b",
     r"\1 pies", re.IGNORECASE),
    (r"\b(\d+) foot\b",
     r"\1 pies", re.IGNORECASE),
    (r"\b(\d+) miles?\b",
     r"\1 millas", re.IGNORECASE),
    (r"\b(\d+) yards?\b",
     r"\1 yardas", re.IGNORECASE),
    (r"\bSelf\b(?!\w)",
     r"Uno mismo", re.IGNORECASE),
    (r"\bTouch\b(?!\w)",
     r"Toque", re.IGNORECASE),
    (r"\bSight\b(?!\w)",
     r"Vista", re.IGNORECASE),
    (r"\bUnlimited\b(?!\w)",
     r"Ilimitado", re.IGNORECASE),
    (r"\bSpecial\b(?!\w)",
     r"Especial", re.IGNORECASE),

    # =========================================================
    # TARGET / CREATURE
    # =========================================================
    (r"\bthe target\b",
     r"el objetivo", re.IGNORECASE),
    (r"\ba target\b",
     r"un objetivo", re.IGNORECASE),
    (r"\bthe targets?\b",
     r"el objetivo", re.IGNORECASE),
    (r"\beach target\b",
     r"cada objetivo", re.IGNORECASE),
    (r"\bone target\b",
     r"un objetivo", re.IGNORECASE),
    (r"\bthe chosen target\b",
     r"el objetivo elegido", re.IGNORECASE),
    (r"\bwilling creature\b",
     r"criatura dispuesta", re.IGNORECASE),
    (r"\bwilling creatures?\b",
     r"criaturas dispuestas", re.IGNORECASE),
    (r"\beach creature\b",
     r"cada criatura", re.IGNORECASE),
    (r"\bevery creature\b",
     r"cada criatura", re.IGNORECASE),
    (r"\ball creatures?\b",
     r"todas las criaturas", re.IGNORECASE),
    (r"\ba creature\b",
     r"una criatura", re.IGNORECASE),
    (r"\bthe creature\b",
     r"la criatura", re.IGNORECASE),
    (r"\bany creature\b",
     r"cualquier criatura", re.IGNORECASE),
    (r"\bother creatures?\b",
     r"otras criaturas", re.IGNORECASE),
    (r"\bhostile creatures?\b",
     r"criaturas hostiles", re.IGNORECASE),
    (r"\bfriendly creatures?\b",
     r"criaturas aliadas", re.IGNORECASE),
    (r"\bliving creature\b",
     r"criatura viva", re.IGNORECASE),
    (r"\bundead creatures?\b",
     r"criaturas no muertas", re.IGNORECASE),
    (r"\bthe undead\b",
     r"los no muertos", re.IGNORECASE),
    (r"\bcreatures?\b",
     r"criaturas", re.IGNORECASE),
    (r"\bcreature\b",
     r"criatura", re.IGNORECASE),

    # =========================================================
    # SPELL ATTACK / ATTACK ROLLS
    # =========================================================
    (r"\branged spell attack\b",
     r"ataque de conjuro a distancia", re.IGNORECASE),
    (r"\bmelee spell attack\b",
     r"ataque de conjuro cuerpo a cuerpo", re.IGNORECASE),
    (r"\bspell attack roll\b",
     r"tirada de ataque de conjuro", re.IGNORECASE),
    (r"\bspell attack\b",
     r"ataque de conjuro", re.IGNORECASE),
    (r"\bmelee weapon attack\b",
     r"ataque de arma cuerpo a cuerpo", re.IGNORECASE),
    (r"\branged weapon attack\b",
     r"ataque de arma a distancia", re.IGNORECASE),
    (r"\battack roll\b",
     r"tirada de ataque", re.IGNORECASE),
    (r"\battack rolls?\b",
     r"tiradas de ataque", re.IGNORECASE),
    (r"\bmake a melee attack\b",
     r"realizar un ataque cuerpo a cuerpo", re.IGNORECASE),
    (r"\bmake a ranged attack\b",
     r"realizar un ataque a distancia", re.IGNORECASE),
    (r"\bmake an attack\b",
     r"realizar un ataque", re.IGNORECASE),
    (r"\bon a hit\b",
     r"en un impacto", re.IGNORECASE),
    (r"\bon a miss\b",
     r"si falla", re.IGNORECASE),
    (r"\bcritical hit\b",
     r"golpe crítico", re.IGNORECASE),

    # =========================================================
    # SPELLS / CONJURO
    # =========================================================
    (r"\bthis spell's? damage\b",
     r"el daño de este conjuro", re.IGNORECASE),
    (r"\bthe spell's? damage\b",
     r"el daño del conjuro", re.IGNORECASE),
    (r"\bthis spell\b",
     r"este conjuro", re.IGNORECASE),
    (r"\bthe spell\b",
     r"el conjuro", re.IGNORECASE),
    (r"\ba spell\b",
     r"un conjuro", re.IGNORECASE),
    (r"\bthe spells?\b",
     r"los conjuros", re.IGNORECASE),
    (r"\bspellcasting ability\b",
     r"habilidad de lanzar conjuros", re.IGNORECASE),
    (r"\bspellcasting focus\b",
     r"foco de lanzamiento de conjuros", re.IGNORECASE),
    (r"\bspell save DC\b",
     r"CD de salvación de conjuro", re.IGNORECASE),
    (r"\bspell damage\b",
     r"daño de conjuro", re.IGNORECASE),
    (r"\bspell level\b",
     r"nivel del conjuro", re.IGNORECASE),
    (r"\bspell effects?\b",
     r"efectos del conjuro", re.IGNORECASE),
    (r"\bspell's? area\b",
     r"área del conjuro", re.IGNORECASE),
    (r"\bspell's? range\b",
     r"alcance del conjuro", re.IGNORECASE),
    (r"\bspell's? duration\b",
     r"duración del conjuro", re.IGNORECASE),

    # =========================================================
    # MOVEMENT / POSITION
    # =========================================================
    (r"\bmovement speed\b",
     r"velocidad de movimiento", re.IGNORECASE),
    (r"\bwalking speed\b",
     r"velocidad de caminar", re.IGNORECASE),
    (r"\bflying speed\b",
     r"velocidad de vuelo", re.IGNORECASE),
    (r"\bswimming speed\b",
     r"velocidad de natación", re.IGNORECASE),
    (r"\bclimbing speed\b",
     r"velocidad de escalada", re.IGNORECASE),
    (r"\bburrowing speed\b",
     r"velocidad de excavación", re.IGNORECASE),
    (r"\bspeed\b",
     r"velocidad", re.IGNORECASE),
    (r"\bdifficult terrain\b",
     r"terreno difícil", re.IGNORECASE),
    (r"\bfall(?:ing|s)? prone\b",
     r"caer tumbado", re.IGNORECASE),
    (r"\bknocked prone\b",
     r"derribado", re.IGNORECASE),
    (r"\bpushed? (\d+) feet?\b",
     r"empujado \1 pies", re.IGNORECASE),
    (r"\bpulled? (\d+) feet?\b",
     r"atraído \1 pies", re.IGNORECASE),
    (r"\bmove up to\b",
     r"moverte hasta", re.IGNORECASE),
    (r"\bcannot move\b",
     r"no puede moverse", re.IGNORECASE),
    (r"\bcan't move\b",
     r"no puede moverse", re.IGNORECASE),

    # =========================================================
    # COMMON PHRASES
    # =========================================================
    (r"\bmust succeed on a\b",
     r"debe tener éxito en una", re.IGNORECASE),
    (r"\bmust make a\b",
     r"debe hacer una", re.IGNORECASE),
    (r"\bfor the duration\b",
     r"durante la duración", re.IGNORECASE),
    (r"\buntil the spell ends\b",
     r"hasta que el conjuro termine", re.IGNORECASE),
    (r"\buntil the end of\b",
     r"hasta el final de", re.IGNORECASE),
    (r"\bat the end of\b",
     r"al final de", re.IGNORECASE),
    (r"\bat the start of\b",
     r"al comienzo de", re.IGNORECASE),
    (r"\bat the beginning of\b",
     r"al comienzo de", re.IGNORECASE),
    (r"\bon each of its turns?\b",
     r"en cada uno de sus turnos", re.IGNORECASE),
    (r"\bon its next turn\b",
     r"en su siguiente turno", re.IGNORECASE),
    (r"\bon your next turn\b",
     r"en tu siguiente turno", re.IGNORECASE),
    (r"\bon your turn\b",
     r"en tu turno", re.IGNORECASE),
    (r"\bon its turn\b",
     r"en su turno", re.IGNORECASE),
    (r"\buntil the end of (?:your|its) next turn\b",
     r"hasta el final de su siguiente turno", re.IGNORECASE),
    (r"\bnumber equal to\b",
     r"número igual a", re.IGNORECASE),
    (r"\bequal to your\b",
     r"igual a tu", re.IGNORECASE),
    (r"\ba number of\b",
     r"un número de", re.IGNORECASE),
    (r"\bno more than\b",
     r"no más de", re.IGNORECASE),
    (r"\bat most\b",
     r"como máximo", re.IGNORECASE),
    (r"\bat least\b",
     r"al menos", re.IGNORECASE),
    (r"\bmore than\b",
     r"más de", re.IGNORECASE),
    (r"\bless than\b",
     r"menos de", re.IGNORECASE),
    (r"\bup to\b",
     r"hasta", re.IGNORECASE),
    (r"\bup to (\w+) times?\b",
     r"hasta \1 veces", re.IGNORECASE),
    (r"\bonce per\b",
     r"una vez por", re.IGNORECASE),
    (r"\bonce per turn\b",
     r"una vez por turno", re.IGNORECASE),
    (r"\bonce per round\b",
     r"una vez por ronda", re.IGNORECASE),
    (r"\bonce per day\b",
     r"una vez por día", re.IGNORECASE),
    (r"\bas long as\b",
     r"siempre que", re.IGNORECASE),
    (r"\bprovided that\b",
     r"siempre que", re.IGNORECASE),
    (r"\bin addition to\b",
     r"además de", re.IGNORECASE),
    (r"\bin addition\b",
     r"además", re.IGNORECASE),
    (r"\bfor each\b",
     r"por cada", re.IGNORECASE),
    (r"\bfor every\b",
     r"por cada", re.IGNORECASE),
    (r"\binstead of\b",
     r"en lugar de", re.IGNORECASE),
    (r"\binstead\b",
     r"en cambio", re.IGNORECASE),
    (r"\bregardless of\b",
     r"independientemente de", re.IGNORECASE),
    (r"\bin place of\b",
     r"en lugar de", re.IGNORECASE),
    (r"\bas well as\b",
     r"así como", re.IGNORECASE),
    (r"\bwhen it first enters\b",
     r"cuando entra por primera vez en", re.IGNORECASE),
    (r"\bwhen it enters\b",
     r"cuando entra en", re.IGNORECASE),
    (r"\bon each creature\b",
     r"en cada criatura", re.IGNORECASE),
    (r"\bfor each creature\b",
     r"por cada criatura", re.IGNORECASE),
    (r"\beach round\b",
     r"cada ronda", re.IGNORECASE),
    (r"\beach turn\b",
     r"cada turno", re.IGNORECASE),

    # =========================================================
    # ADVANTAGE / DISADVANTAGE / PROFICIENCY
    # =========================================================
    (r"\bhave advantage\b",
     r"tener ventaja", re.IGNORECASE),
    (r"\bhave disadvantage\b",
     r"tener desventaja", re.IGNORECASE),
    (r"\badvantage on\b",
     r"ventaja en", re.IGNORECASE),
    (r"\bdisadvantage on\b",
     r"desventaja en", re.IGNORECASE),
    (r"\badvantage or disadvantage\b",
     r"ventaja o desventaja", re.IGNORECASE),
    (r"\badvantage\b",
     r"ventaja", re.IGNORECASE),
    (r"\bdisadvantage\b",
     r"desventaja", re.IGNORECASE),
    (r"\bproficiency bonus\b",
     r"bonificador de competencia", re.IGNORECASE),
    (r"\bproficiency\b",
     r"competencia", re.IGNORECASE),
    (r"\bproficient\b",
     r"competente", re.IGNORECASE),

    # =========================================================
    # CHECKS / SKILLS
    # =========================================================
    (r"\bability check\b",
     r"prueba de característica", re.IGNORECASE),
    (r"\bability checks?\b",
     r"pruebas de característica", re.IGNORECASE),
    (r"\bskill check\b",
     r"prueba de habilidad", re.IGNORECASE),
    (r"\bAthletics check\b",
     r"prueba de Atletismo", re.IGNORECASE),
    (r"\bAcrobatics check\b",
     r"prueba de Acrobacias", re.IGNORECASE),
    (r"\bStealth check\b",
     r"prueba de Sigilo", re.IGNORECASE),
    (r"\bPerception check\b",
     r"prueba de Percepción", re.IGNORECASE),
    (r"\bInvestigation check\b",
     r"prueba de Investigación", re.IGNORECASE),
    (r"\bHistory check\b",
     r"prueba de Historia", re.IGNORECASE),
    (r"\bArcana check\b",
     r"prueba de Conocimiento Arcano", re.IGNORECASE),
    (r"\bNature check\b",
     r"prueba de Naturaleza", re.IGNORECASE),
    (r"\bReligion check\b",
     r"prueba de Religión", re.IGNORECASE),
    (r"\bSurvival check\b",
     r"prueba de Supervivencia", re.IGNORECASE),
    (r"\bMedicine check\b",
     r"prueba de Medicina", re.IGNORECASE),
    (r"\bAnimal Handling check\b",
     r"prueba de Trato con Animales", re.IGNORECASE),
    (r"\bDeception check\b",
     r"prueba de Engaño", re.IGNORECASE),
    (r"\bPersuasion check\b",
     r"prueba de Persuasión", re.IGNORECASE),
    (r"\bIntimidation check\b",
     r"prueba de Intimidación", re.IGNORECASE),
    (r"\bSleight of Hand check\b",
     r"prueba de Juego de Manos", re.IGNORECASE),
    (r"\bInsight check\b",
     r"prueba de Perspicacia", re.IGNORECASE),
    (r"\bPerformance check\b",
     r"prueba de Interpretación", re.IGNORECASE),

    # =========================================================
    # SPELLCASTING
    # =========================================================
    (r"\bspell component\b",
     r"componente del conjuro", re.IGNORECASE),
    (r"\bverbal component\b",
     r"componente verbal", re.IGNORECASE),
    (r"\bsomatic component\b",
     r"componente somático", re.IGNORECASE),
    (r"\bmaterial component\b",
     r"componente material", re.IGNORECASE),
    (r"\bthe caster\b",
     r"el lanzador", re.IGNORECASE),
    (r"\byour spellcasting ability modifier\b",
     r"tu modificador de característica de lanzamiento de conjuros", re.IGNORECASE),
    (r"\byour spell save DC\b",
     r"tu CD de salvación de conjuro", re.IGNORECASE),
    (r"\bcast as a ritual\b",
     r"lanzado como ritual", re.IGNORECASE),
    (r"\bcast a spell\b",
     r"lanzar un conjuro", re.IGNORECASE),
    (r"\bcasting a spell\b",
     r"lanzar un conjuro", re.IGNORECASE),
    (r"\bcasting time\b",
     r"tiempo de lanzamiento", re.IGNORECASE),

    # =========================================================
    # DURATION / TIME
    # =========================================================
    (r"\bInstantaneous\b",
     r"Instantáneo", re.IGNORECASE),
    (r"\bconcentration, up to (\d+) minute\b",
     r"concentración, hasta \1 minuto", re.IGNORECASE),
    (r"\bconcentration, up to (\d+) minutes?\b",
     r"concentración, hasta \1 minutos", re.IGNORECASE),
    (r"\bconcentration, up to (\d+) hour\b",
     r"concentración, hasta \1 hora", re.IGNORECASE),
    (r"\bconcentration, up to (\d+) hours?\b",
     r"concentración, hasta \1 horas", re.IGNORECASE),
    (r"\bup to (\d+) minutes?\b",
     r"hasta \1 minutos", re.IGNORECASE),
    (r"\bup to (\d+) hours?\b",
     r"hasta \1 horas", re.IGNORECASE),
    (r"\b(\d+) rounds?\b",
     r"\1 rondas", re.IGNORECASE),
    (r"\b(\d+) minutes?\b",
     r"\1 minutos", re.IGNORECASE),
    (r"\b(\d+) hours?\b",
     r"\1 horas", re.IGNORECASE),
    (r"\b(\d+) days?\b",
     r"\1 días", re.IGNORECASE),
    (r"\b(\d+) weeks?\b",
     r"\1 semanas", re.IGNORECASE),
    (r"\b(\d+) months?\b",
     r"\1 meses", re.IGNORECASE),
    (r"\b(\d+) years?\b",
     r"\1 años", re.IGNORECASE),
    (r"\b(\d+) turns?\b",
     r"\1 turnos", re.IGNORECASE),
    (r"\bone minute\b",
     r"un minuto", re.IGNORECASE),
    (r"\bone hour\b",
     r"una hora", re.IGNORECASE),
    (r"\bone day\b",
     r"un día", re.IGNORECASE),
    (r"\bone week\b",
     r"una semana", re.IGNORECASE),
    (r"\bone round\b",
     r"una ronda", re.IGNORECASE),
    (r"\bone turn\b",
     r"un turno", re.IGNORECASE),

    # =========================================================
    # SPECIFIC GAME TERMS
    # =========================================================
    (r"\bdark?vision\b",
     r"visión en la oscuridad", re.IGNORECASE),
    (r"\btruesight\b",
     r"visión verdadera", re.IGNORECASE),
    (r"\bblindsight\b",
     r"visión ciega", re.IGNORECASE),
    (r"\btremorsense\b",
     r"sentido telúrico", re.IGNORECASE),
    (r"\bpassive perception\b",
     r"percepción pasiva", re.IGNORECASE),
    (r"\bpassive Perception\b",
     r"Percepción pasiva", 0),
    (r"\bwarding area\b",
     r"área protegida", re.IGNORECASE),
    (r"\bwarded area\b",
     r"área protegida", re.IGNORECASE),
    (r"\bright?\-of\-way\b",
     r"derecho de paso", re.IGNORECASE),
    (r"\bhalf cover\b",
     r"cobertura parcial", re.IGNORECASE),
    (r"\bthree-quarters cover\b",
     r"cobertura de tres cuartos", re.IGNORECASE),
    (r"\bthree.quarters cover\b",
     r"cobertura de tres cuartos", re.IGNORECASE),
    (r"\btotal cover\b",
     r"cobertura total", re.IGNORECASE),
    (r"\bcover\b",
     r"cobertura", re.IGNORECASE),
    (r"\bextra damage\b",
     r"daño adicional", re.IGNORECASE),
    (r"\badditional damage\b",
     r"daño adicional", re.IGNORECASE),
    (r"\bbonus damage\b",
     r"daño adicional", re.IGNORECASE),
    (r"\bmax(?:imum)? damage\b",
     r"daño máximo", re.IGNORECASE),
    (r"\bminimum damage\b",
     r"daño mínimo", re.IGNORECASE),
    (r"\bdamage roll\b",
     r"tirada de daño", re.IGNORECASE),
    (r"\bdamage type\b",
     r"tipo de daño", re.IGNORECASE),
    (r"\bdamage\b",
     r"daño", re.IGNORECASE),
    (r"\bimmune to\b",
     r"inmune a", re.IGNORECASE),
    (r"\bimmunity to\b",
     r"inmunidad a", re.IGNORECASE),
    (r"\bresistant to\b",
     r"resistente a", re.IGNORECASE),
    (r"\bresistance to\b",
     r"resistencia a", re.IGNORECASE),
    (r"\bvulnerable to\b",
     r"vulnerable a", re.IGNORECASE),
    (r"\bvulnerability to\b",
     r"vulnerabilidad a", re.IGNORECASE),
    (r"\bresistance\b",
     r"resistencia", re.IGNORECASE),
    (r"\bimmunity\b",
     r"inmunidad", re.IGNORECASE),
    (r"\bvulnerability\b",
     r"vulnerabilidad", re.IGNORECASE),
    (r"\bnonmagical\b",
     r"no mágico", re.IGNORECASE),
    (r"\bmagical\b",
     r"mágico", re.IGNORECASE),
    (r"\bsupernatural\b",
     r"sobrenatural", re.IGNORECASE),
    (r"\bsensory organ\b",
     r"órgano sensorial", re.IGNORECASE),
    (r"\bsense\b",
     r"sentido", re.IGNORECASE),

    # =========================================================
    # OBJECT / MATERIAL
    # =========================================================
    (r"\ba tiny\b",
     r"una diminuta", re.IGNORECASE),
    (r"\bTiny\b",
     r"Diminuto", 0),
    (r"\bSmall\b(?=\s+(?:creature|object|beast|humanoid|undead|fiend|celestial|fey|construct|elemental|ooze|plant|dragon|giant|monstrosity|aberration))",
     r"Pequeño", 0),
    (r"\bMedium\b(?=\s+(?:creature|object|beast|humanoid|undead|fiend|celestial|fey|construct|elemental|ooze|plant|dragon|giant|monstrosity|aberration))",
     r"Mediano", 0),
    (r"\bLarge\b(?=\s+(?:creature|object|beast|humanoid|undead|fiend|celestial|fey|construct|elemental|ooze|plant|dragon|giant|monstrosity|aberration))",
     r"Grande", 0),
    (r"\bHuge\b(?=\s+(?:creature|object|beast|humanoid|undead|fiend|celestial|fey|construct|elemental|ooze|plant|dragon|giant|monstrosity|aberration))",
     r"Enorme", 0),
    (r"\bGargantuan\b",
     r"Gargantuesco", re.IGNORECASE),
    (r"\bhumanoid\b",
     r"humanoide", re.IGNORECASE),
    (r"\bbestial\b",
     r"bestial", re.IGNORECASE),
    (r"\b(?:a |the )?beast\b",
     r"bestia", re.IGNORECASE),
    (r"\bundead\b",
     r"no muerto", re.IGNORECASE),
    (r"\bfiend\b",
     r"demonio", re.IGNORECASE),
    (r"\bcelestial\b",
     r"celestial", re.IGNORECASE),
    (r"\belemental\b",
     r"elemental", re.IGNORECASE),
    (r"\bconstruct\b",
     r"constructo", re.IGNORECASE),
    (r"\bfey\b",
     r"feérico", re.IGNORECASE),
    (r"\babberation\b",
     r"aberración", re.IGNORECASE),
    (r"\baberration\b",
     r"aberración", re.IGNORECASE),
    (r"\bmonstrosity\b",
     r"monstruosidad", re.IGNORECASE),
    (r"\bdragon\b",
     r"dragón", re.IGNORECASE),
    (r"\bgiant\b",
     r"gigante", re.IGNORECASE),
    (r"\bplant\b(?!\s+the)",
     r"planta", re.IGNORECASE),
    (r"\bswarm\b",
     r"enjambre", re.IGNORECASE),
    (r"\bskeleton\b",
     r"esqueleto", re.IGNORECASE),
    (r"\bzombie\b",
     r"zombi", re.IGNORECASE),
    (r"\bghoul\b",
     r"ghoul", re.IGNORECASE),
    (r"\bghost\b",
     r"fantasma", re.IGNORECASE),
    (r"\bspecter\b",
     r"espectro", re.IGNORECASE),
    (r"\bwraith\b",
     r"aparición", re.IGNORECASE),
    (r"\bshadow\b",
     r"sombra", re.IGNORECASE),
    (r"\bvampire\b",
     r"vampiro", re.IGNORECASE),
    (r"\blich\b",
     r"liche", re.IGNORECASE),
    (r"\bwerewolf\b",
     r"hombre lobo", re.IGNORECASE),
    (r"\bwerebear\b",
     r"hombre oso", re.IGNORECASE),
    (r"\bgoblin\b",
     r"trasgo", re.IGNORECASE),
    (r"\bkobold\b",
     r"kobold", re.IGNORECASE),
    (r"\borgre\b",
     r"ogro", re.IGNORECASE),
    (r"\bognre\b",
     r"ogro", re.IGNORECASE),
    (r"\btroll\b",
     r"trol", re.IGNORECASE),
    (r"\bserpent\b",
     r"serpiente", re.IGNORECASE),
    (r"\bspider\b",
     r"araña", re.IGNORECASE),
    (r"\brat\b",
     r"rata", re.IGNORECASE),
    (r"\bfish\b",
     r"pez", re.IGNORECASE),
    (r"\bbird\b",
     r"pájaro", re.IGNORECASE),
    (r"\bhorse\b",
     r"caballo", re.IGNORECASE),
    (r"\bdog\b",
     r"perro", re.IGNORECASE),
    (r"\bcat\b",
     r"gato", re.IGNORECASE),
    (r"\bwolf\b",
     r"lobo", re.IGNORECASE),

    # =========================================================
    # COMMON MATERIAL PHRASES
    # =========================================================
    (r"\ba diamond worth at least (\d+) gp\b",
     r"un diamante de al menos \1 po", re.IGNORECASE),
    (r"\bworth at least (\d+) gp\b",
     r"con un valor de al menos \1 po", re.IGNORECASE),
    (r"\bworth (\d+) gp or more\b",
     r"con un valor de \1 po o más", re.IGNORECASE),
    (r"\bworth (\d+) gp\b",
     r"con un valor de \1 po", re.IGNORECASE),
    (r"\b(\d+) gold pieces?\b",
     r"\1 piezas de oro", re.IGNORECASE),
    (r"\bgold pieces?\b",
     r"piezas de oro", re.IGNORECASE),
    (r"\bsilver pieces?\b",
     r"piezas de plata", re.IGNORECASE),
    (r"\bcopper pieces?\b",
     r"piezas de cobre", re.IGNORECASE),
    (r"\belectrum pieces?\b",
     r"piezas de electro", re.IGNORECASE),
    (r"\bplatinum pieces?\b",
     r"piezas de platino", re.IGNORECASE),
    (r"\bgp\b",
     r"po", re.IGNORECASE),
    (r"\bsp\b",
     r"pp", re.IGNORECASE),
    (r"\bcp\b",
     r"pc", re.IGNORECASE),
    (r"\ba piece of\b",
     r"un trozo de", re.IGNORECASE),
    (r"\ba pinch of\b",
     r"una pizca de", re.IGNORECASE),
    (r"\ba drop of\b",
     r"una gota de", re.IGNORECASE),
    (r"\ba vial of\b",
     r"un frasco de", re.IGNORECASE),
    (r"\ba bit of\b",
     r"un poco de", re.IGNORECASE),
    (r"\ba small amount of\b",
     r"una pequeña cantidad de", re.IGNORECASE),
    (r"\ba handful of\b",
     r"un puñado de", re.IGNORECASE),
    (r"\ba strip of\b",
     r"una tira de", re.IGNORECASE),
    (r"\ba sprig of\b",
     r"una ramita de", re.IGNORECASE),
    (r"\ba clump of\b",
     r"un trozo de", re.IGNORECASE),
    (r"\ba lock of\b",
     r"un mechón de", re.IGNORECASE),
    (r"\ba chip of\b",
     r"una astilla de", re.IGNORECASE),
    (r"\ba shard of\b",
     r"un fragmento de", re.IGNORECASE),
    (r"\ba gem worth\b",
     r"una gema con un valor de", re.IGNORECASE),
    (r"\ba gemstone\b",
     r"una piedra preciosa", re.IGNORECASE),
    (r"\ba gem\b",
     r"una gema", re.IGNORECASE),
    (r"\ba pearl\b",
     r"una perla", re.IGNORECASE),
    (r"\ba diamond\b",
     r"un diamante", re.IGNORECASE),
    (r"\bashes?\b",
     r"cenizas", re.IGNORECASE),
    (r"\bherbs?\b",
     r"hierbas", re.IGNORECASE),
    (r"\bincense\b",
     r"incienso", re.IGNORECASE),
    (r"\bcandle\b",
     r"vela", re.IGNORECASE),
    (r"\bchalk\b",
     r"tiza", re.IGNORECASE),
    (r"\bcoal\b",
     r"carbón", re.IGNORECASE),
    (r"\bclay\b",
     r"arcilla", re.IGNORECASE),
    (r"\blead\b",
     r"plomo", re.IGNORECASE),
    (r"\biron\b",
     r"hierro", re.IGNORECASE),
    (r"\bcopper\b",
     r"cobre", re.IGNORECASE),
    (r"\bsilver\b",
     r"plata", re.IGNORECASE),
    (r"\bgold\b",
     r"oro", re.IGNORECASE),
    (r"\bplatinum\b",
     r"platino", re.IGNORECASE),
    (r"\bwood\b",
     r"madera", re.IGNORECASE),
    (r"\bstone\b",
     r"piedra", re.IGNORECASE),
    (r"\bfur\b",
     r"piel", re.IGNORECASE),
    (r"\bleather\b",
     r"cuero", re.IGNORECASE),
    (r"\bbone\b",
     r"hueso", re.IGNORECASE),
    (r"\bblood\b",
     r"sangre", re.IGNORECASE),
    (r"\btear\b",
     r"lágrima", re.IGNORECASE),
    (r"\bfeather\b",
     r"pluma", re.IGNORECASE),
    (r"\bstring\b",
     r"hilo", re.IGNORECASE),
    (r"\bthread\b",
     r"hilo", re.IGNORECASE),
    (r"\bwire\b",
     r"alambre", re.IGNORECASE),
    (r"\bbell\b",
     r"campana", re.IGNORECASE),
    (r"\bcrystal\b",
     r"cristal", re.IGNORECASE),
    (r"\bglass\b",
     r"vidrio", re.IGNORECASE),
    (r"\boil\b",
     r"aceite", re.IGNORECASE),
    (r"\bwater\b",
     r"agua", re.IGNORECASE),
    (r"\bfire\b",
     r"fuego", re.IGNORECASE),
    (r"\bearth\b",
     r"tierra", re.IGNORECASE),
    (r"\bair\b",
     r"aire", re.IGNORECASE),
    (r"\bsalt\b",
     r"sal", re.IGNORECASE),
    (r"\bsugar\b",
     r"azúcar", re.IGNORECASE),
    (r"\bmoss\b",
     r"musgo", re.IGNORECASE),
    (r"\bmud\b",
     r"barro", re.IGNORECASE),
    (r"\bsand\b",
     r"arena", re.IGNORECASE),
    (r"\bdirt\b",
     r"tierra", re.IGNORECASE),
    (r"\bdust\b",
     r"polvo", re.IGNORECASE),
    (r"\bpowder\b",
     r"polvo", re.IGNORECASE),
    (r"\bwax\b",
     r"cera", re.IGNORECASE),
    (r"\btar\b",
     r"alquitrán", re.IGNORECASE),
    (r"\bsap\b",
     r"savia", re.IGNORECASE),
    (r"\bresin\b",
     r"resina", re.IGNORECASE),
    (r"\bparchment\b",
     r"pergamino", re.IGNORECASE),
    (r"\bpaper\b",
     r"papel", re.IGNORECASE),

    # =========================================================
    # ANATOMY / BODY
    # =========================================================
    (r"\bfingernail\b",
     r"uña", re.IGNORECASE),
    (r"\bfinger\b",
     r"dedo", re.IGNORECASE),
    (r"\bhand\b",
     r"mano", re.IGNORECASE),
    (r"\barm\b",
     r"brazo", re.IGNORECASE),
    (r"\bleg\b",
     r"pierna", re.IGNORECASE),
    (r"\bfoot\b",
     r"pie", re.IGNORECASE),
    (r"\bhead\b",
     r"cabeza", re.IGNORECASE),
    (r"\beye\b",
     r"ojo", re.IGNORECASE),
    (r"\bear\b",
     r"oído", re.IGNORECASE),
    (r"\bnose\b",
     r"nariz", re.IGNORECASE),
    (r"\bmouth\b",
     r"boca", re.IGNORECASE),
    (r"\bneck\b",
     r"cuello", re.IGNORECASE),
    (r"\bchest\b",
     r"pecho", re.IGNORECASE),
    (r"\bback\b",
     r"espalda", re.IGNORECASE),
    (r"\bbody\b",
     r"cuerpo", re.IGNORECASE),
    (r"\bskin\b",
     r"piel", re.IGNORECASE),
    (r"\bflesh\b",
     r"carne", re.IGNORECASE),
    (r"\bsoul\b",
     r"alma", re.IGNORECASE),
    (r"\bmind\b",
     r"mente", re.IGNORECASE),
    (r"\bheart\b",
     r"corazón", re.IGNORECASE),
    (r"\bspirit\b",
     r"espíritu", re.IGNORECASE),

    # =========================================================
    # TERRAIN / ENVIRONMENT
    # =========================================================
    (r"\bunoccupied space\b",
     r"espacio desocupado", re.IGNORECASE),
    (r"\bunoccupied spaces?\b",
     r"espacios desocupados", re.IGNORECASE),
    (r"\bopen space\b",
     r"espacio abierto", re.IGNORECASE),
    (r"\bsolid surface\b",
     r"superficie sólida", re.IGNORECASE),
    (r"\bsolid ground\b",
     r"terreno sólido", re.IGNORECASE),
    (r"\bsolid floor\b",
     r"suelo sólido", re.IGNORECASE),
    (r"\bsolid object\b",
     r"objeto sólido", re.IGNORECASE),
    (r"\ba point on the ground\b",
     r"un punto en el suelo", re.IGNORECASE),
    (r"\ba point you can see\b",
     r"un punto que puedas ver", re.IGNORECASE),
    (r"\ba point within range\b",
     r"un punto dentro del alcance", re.IGNORECASE),
    (r"\ba spot within range\b",
     r"un lugar dentro del alcance", re.IGNORECASE),
    (r"\ban area\b",
     r"una zona", re.IGNORECASE),
    (r"\bthe area\b",
     r"la zona", re.IGNORECASE),
    (r"\bthe affected area\b",
     r"el área afectada", re.IGNORECASE),
    (r"\bthe spell's area\b",
     r"el área del conjuro", re.IGNORECASE),
    (r"\bthe ground\b",
     r"el suelo", re.IGNORECASE),
    (r"\bthe floor\b",
     r"el suelo", re.IGNORECASE),
    (r"\bthe ceiling\b",
     r"el techo", re.IGNORECASE),
    (r"\bthe wall\b",
     r"la pared", re.IGNORECASE),
    (r"\bthe walls?\b",
     r"las paredes", re.IGNORECASE),
    (r"\bthe surface\b",
     r"la superficie", re.IGNORECASE),
    (r"\bthe center\b",
     r"el centro", re.IGNORECASE),
    (r"\bthe centre\b",
     r"el centro", re.IGNORECASE),
    (r"\bthe edge\b",
     r"el borde", re.IGNORECASE),
    (r"\bthe border\b",
     r"el límite", re.IGNORECASE),
    (r"\bthe interior\b",
     r"el interior", re.IGNORECASE),
    (r"\bthe exterior\b",
     r"el exterior", re.IGNORECASE),
    (r"\bthe outer\b",
     r"el exterior", re.IGNORECASE),
    (r"\bthe inner\b",
     r"el interior", re.IGNORECASE),
    (r"\bthe nearest\b",
     r"el más cercano", re.IGNORECASE),

    # =========================================================
    # LIGHT / VISIBILITY
    # =========================================================
    (r"\bbright light\b",
     r"luz brillante", re.IGNORECASE),
    (r"\bdim light\b",
     r"luz tenue", re.IGNORECASE),
    (r"\bdarkness\b",
     r"oscuridad", re.IGNORECASE),
    (r"\blight\b",
     r"luz", re.IGNORECASE),
    (r"\billuminate\b",
     r"iluminar", re.IGNORECASE),
    (r"\bshed light\b",
     r"emitir luz", re.IGNORECASE),
    (r"\bblindly\b",
     r"a ciegas", re.IGNORECASE),
    (r"\bblind\b",
     r"cegar", re.IGNORECASE),
    (r"\bsee\b",
     r"ver", re.IGNORECASE),
    (r"\bvisible\b",
     r"visible", re.IGNORECASE),
    (r"\binvisible\b",
     r"invisible", re.IGNORECASE),
    (r"\bobscured\b",
     r"oscurecido", re.IGNORECASE),
    (r"\bheavily obscured\b",
     r"fuertemente oscurecido", re.IGNORECASE),
    (r"\blightly obscured\b",
     r"ligeramente oscurecido", re.IGNORECASE),

    # =========================================================
    # SENSE / PERCEPTION
    # =========================================================
    (r"\bhear\b",
     r"escuchar", re.IGNORECASE),
    (r"\bsmell\b",
     r"oler", re.IGNORECASE),
    (r"\btouch\b",
     r"tocar", re.IGNORECASE),
    (r"\bperceive\b",
     r"percibir", re.IGNORECASE),
    (r"\bsense\b",
     r"sentir", re.IGNORECASE),

    # =========================================================
    # DICE ROLLS
    # =========================================================
    (r"\broll (\d+d\d+)\b",
     r"tira \1", re.IGNORECASE),
    (r"\brolling (\d+d\d+)\b",
     r"tirando \1", re.IGNORECASE),
    (r"\b(\d+d\d+) dice\b",
     r"\1 dados", re.IGNORECASE),
    (r"\bone die\b",
     r"un dado", re.IGNORECASE),
    (r"\bdie\b",
     r"dado", re.IGNORECASE),

    # =========================================================
    # COMMON CONNECTORS / MISC
    # =========================================================
    (r"\bhowever\b",
     r"sin embargo", re.IGNORECASE),
    (r"\btherefore\b",
     r"por lo tanto", re.IGNORECASE),
    (r"\bthus\b",
     r"así", re.IGNORECASE),
    (r"\bhence\b",
     r"de ahí que", re.IGNORECASE),
    (r"\bmoreover\b",
     r"además", re.IGNORECASE),
    (r"\bfurthermore\b",
     r"además", re.IGNORECASE),
    (r"\bnevertheless\b",
     r"sin embargo", re.IGNORECASE),
    (r"\botherwise\b",
     r"de lo contrario", re.IGNORECASE),
    (r"\baccordingly\b",
     r"en consecuencia", re.IGNORECASE),
    (r"\bsubsequently\b",
     r"posteriormente", re.IGNORECASE),
    (r"\binitially\b",
     r"inicialmente", re.IGNORECASE),
    (r"\bimmediately\b",
     r"inmediatamente", re.IGNORECASE),
    (r"\bsimultaneously\b",
     r"simultáneamente", re.IGNORECASE),
    (r"\bgradually\b",
     r"gradualmente", re.IGNORECASE),
    (r"\bvoluntarily\b",
     r"voluntariamente", re.IGNORECASE),
    (r"\bautomatically\b",
     r"automáticamente", re.IGNORECASE),
    (r"\bnormally\b",
     r"normalmente", re.IGNORECASE),
    (r"\bpermanently\b",
     r"permanentemente", re.IGNORECASE),
    (r"\btemporarily\b",
     r"temporalmente", re.IGNORECASE),
    (r"\bphysically\b",
     r"físicamente", re.IGNORECASE),
    (r"\bmagically\b",
     r"mágicamente", re.IGNORECASE),
    (r"\bmentally\b",
     r"mentalmente", re.IGNORECASE),
    (r"\bverbally\b",
     r"verbalmente", re.IGNORECASE),
    (r"\bspecifically\b",
     r"específicamente", re.IGNORECASE),
    (r"\bentirely\b",
     r"completamente", re.IGNORECASE),
    (r"\bcompletely\b",
     r"completamente", re.IGNORECASE),
    (r"\bpartially\b",
     r"parcialmente", re.IGNORECASE),
    (r"\bapparently\b",
     r"aparentemente", re.IGNORECASE),
    (r"\beffectively\b",
     r"efectivamente", re.IGNORECASE),
    (r"\baccurately\b",
     r"con precisión", re.IGNORECASE),
    (r"\bcoherently\b",
     r"coherentemente", re.IGNORECASE),
    (r"\bconsecutively\b",
     r"consecutivamente", re.IGNORECASE),
    (r"\bcontinuously\b",
     r"continuamente", re.IGNORECASE),
    (r"\bcurrently\b",
     r"actualmente", re.IGNORECASE),
    (r"\bdirectly\b",
     r"directamente", re.IGNORECASE),
    (r"\bequally\b",
     r"igualmente", re.IGNORECASE),
    (r"\bhalf the damage\b",
     r"la mitad del daño", re.IGNORECASE),
    (r"\bdouble the damage\b",
     r"el doble del daño", re.IGNORECASE),
    (r"\btwice the damage\b",
     r"el doble del daño", re.IGNORECASE),
    (r"\bthe full damage\b",
     r"el daño total", re.IGNORECASE),
    (r"\bdouble damage\b",
     r"el doble de daño", re.IGNORECASE),

    # =========================================================
    # LEVEL ORDINALS
    # =========================================================
    (r"\b1st.level\b",
     r"nivel 1", re.IGNORECASE),
    (r"\b2nd.level\b",
     r"nivel 2", re.IGNORECASE),
    (r"\b3rd.level\b",
     r"nivel 3", re.IGNORECASE),
    (r"\b4th.level\b",
     r"nivel 4", re.IGNORECASE),
    (r"\b5th.level\b",
     r"nivel 5", re.IGNORECASE),
    (r"\b6th.level\b",
     r"nivel 6", re.IGNORECASE),
    (r"\b7th.level\b",
     r"nivel 7", re.IGNORECASE),
    (r"\b8th.level\b",
     r"nivel 8", re.IGNORECASE),
    (r"\b9th.level\b",
     r"nivel 9", re.IGNORECASE),
    (r"\b1st level\b",
     r"nivel 1", re.IGNORECASE),
    (r"\b2nd level\b",
     r"nivel 2", re.IGNORECASE),
    (r"\b3rd level\b",
     r"nivel 3", re.IGNORECASE),
    (r"\b4th level\b",
     r"nivel 4", re.IGNORECASE),
    (r"\b5th level\b",
     r"nivel 5", re.IGNORECASE),
    (r"\b6th level\b",
     r"nivel 6", re.IGNORECASE),
    (r"\b7th level\b",
     r"nivel 7", re.IGNORECASE),
    (r"\b8th level\b",
     r"nivel 8", re.IGNORECASE),
    (r"\b9th level\b",
     r"nivel 9", re.IGNORECASE),

    # =========================================================
    # COMMON ADJECTIVES / NOUNS
    # =========================================================
    (r"\bthe duration\b",
     r"la duración", re.IGNORECASE),
    (r"\bthe effect\b",
     r"el efecto", re.IGNORECASE),
    (r"\bthe effects?\b",
     r"los efectos", re.IGNORECASE),
    (r"\bthe spell\b",
     r"el conjuro", re.IGNORECASE),
    (r"\bthe caster\b",
     r"el lanzador", re.IGNORECASE),
    (r"\bthe trigger\b",
     r"el desencadenante", re.IGNORECASE),
    (r"\bthe source\b",
     r"la fuente", re.IGNORECASE),
    (r"\bthe origin\b",
     r"el origen", re.IGNORECASE),
    (r"\bthe range\b",
     r"el alcance", re.IGNORECASE),
    (r"\bthe radius\b",
     r"el radio", re.IGNORECASE),
    (r"\bthe cone\b",
     r"el cono", re.IGNORECASE),
    (r"\bthe line\b",
     r"la línea", re.IGNORECASE),
    (r"\bthe sphere\b",
     r"la esfera", re.IGNORECASE),
    (r"\bthe cube\b",
     r"el cubo", re.IGNORECASE),
    (r"\bthe cylinder\b",
     r"el cilindro", re.IGNORECASE),
    (r"\bthe nearest\b",
     r"el más cercano", re.IGNORECASE),
    (r"\bthe farthest\b",
     r"el más lejano", re.IGNORECASE),
    (r"\bthe lowest\b",
     r"el más bajo", re.IGNORECASE),
    (r"\bthe highest\b",
     r"el más alto", re.IGNORECASE),
    (r"\bthe same\b",
     r"el mismo", re.IGNORECASE),
    (r"\bthe following\b",
     r"lo siguiente", re.IGNORECASE),
    (r"\bthe next\b",
     r"el siguiente", re.IGNORECASE),
    (r"\bthe previous\b",
     r"el anterior", re.IGNORECASE),
    (r"\bthe original\b",
     r"el original", re.IGNORECASE),
    (r"\bthe new\b",
     r"el nuevo", re.IGNORECASE),
    (r"\bthe old\b",
     r"el antiguo", re.IGNORECASE),
    (r"\bthe last\b",
     r"el último", re.IGNORECASE),
    (r"\bthe first\b",
     r"el primero", re.IGNORECASE),
    (r"\bthe second\b",
     r"el segundo", re.IGNORECASE),
    (r"\bthe third\b",
     r"el tercero", re.IGNORECASE),
    (r"\ba number\b",
     r"un número", re.IGNORECASE),
    (r"\bfor instance\b",
     r"por ejemplo", re.IGNORECASE),
    (r"\bfor example\b",
     r"por ejemplo", re.IGNORECASE),
    (r"\bsuch as\b",
     r"como", re.IGNORECASE),

    # =========================================================
    # NUMBERS / ORDINALS
    # =========================================================
    (r"\b(first|1st)\b(?!\s*level)",
     r"primero", re.IGNORECASE),
    (r"\b(second|2nd)\b(?!\s*level)",
     r"segundo", re.IGNORECASE),
    (r"\b(third|3rd)\b(?!\s*level)",
     r"tercero", re.IGNORECASE),
    (r"\b(fourth|4th)\b(?!\s*level)",
     r"cuarto", re.IGNORECASE),
    (r"\b(fifth|5th)\b(?!\s*level)",
     r"quinto", re.IGNORECASE),
    (r"\b(sixth|6th)\b(?!\s*level)",
     r"sexto", re.IGNORECASE),
    (r"\b(seventh|7th)\b(?!\s*level)",
     r"séptimo", re.IGNORECASE),
    (r"\b(eighth|8th)\b(?!\s*level)",
     r"octavo", re.IGNORECASE),
    (r"\b(ninth|9th)\b(?!\s*level)",
     r"noveno", re.IGNORECASE),
    (r"\bone\b",
     r"uno", re.IGNORECASE),
    (r"\btwo\b",
     r"dos", re.IGNORECASE),
    (r"\bthree\b",
     r"tres", re.IGNORECASE),
    (r"\bfour\b",
     r"cuatro", re.IGNORECASE),
    (r"\bfive\b",
     r"cinco", re.IGNORECASE),
    (r"\bsix\b",
     r"seis", re.IGNORECASE),
    (r"\bseven\b",
     r"siete", re.IGNORECASE),
    (r"\beight\b",
     r"ocho", re.IGNORECASE),
    (r"\bnine\b",
     r"nueve", re.IGNORECASE),
    (r"\bten\b",
     r"diez", re.IGNORECASE),
    (r"\beleven\b",
     r"once", re.IGNORECASE),
    (r"\btwelve\b",
     r"doce", re.IGNORECASE),
    (r"\bthirteen\b",
     r"trece", re.IGNORECASE),
    (r"\bfourteen\b",
     r"catorce", re.IGNORECASE),
    (r"\bfifteen\b",
     r"quince", re.IGNORECASE),
    (r"\bsixteen\b",
     r"dieciséis", re.IGNORECASE),
    (r"\bseventeen\b",
     r"diecisiete", re.IGNORECASE),
    (r"\beighteen\b",
     r"dieciocho", re.IGNORECASE),
    (r"\bnineteen\b",
     r"diecinueve", re.IGNORECASE),
    (r"\btwenty\b",
     r"veinte", re.IGNORECASE),
    (r"\bthirty\b",
     r"treinta", re.IGNORECASE),
    (r"\bforty\b",
     r"cuarenta", re.IGNORECASE),
    (r"\bfifty\b",
     r"cincuenta", re.IGNORECASE),
    (r"\bsixty\b",
     r"sesenta", re.IGNORECASE),
    (r"\bseventy\b",
     r"setenta", re.IGNORECASE),
    (r"\beighty\b",
     r"ochenta", re.IGNORECASE),
    (r"\bninety\b",
     r"noventa", re.IGNORECASE),
    (r"\ba hundred\b",
     r"cien", re.IGNORECASE),
    (r"\bone hundred\b",
     r"cien", re.IGNORECASE),

    # =========================================================
    # WEAPONS / EQUIPMENT
    # =========================================================
    (r"\bsword\b",
     r"espada", re.IGNORECASE),
    (r"\bdagger\b",
     r"daga", re.IGNORECASE),
    (r"\bstaff\b",
     r"bastón", re.IGNORECASE),
    (r"\bwand\b",
     r"varita", re.IGNORECASE),
    (r"\borb\b",
     r"orbe", re.IGNORECASE),
    (r"\brod\b",
     r"vara", re.IGNORECASE),
    (r"\bbow\b",
     r"arco", re.IGNORECASE),
    (r"\bshield\b",
     r"escudo", re.IGNORECASE),
    (r"\bweapon\b",
     r"arma", re.IGNORECASE),
    (r"\bweapons?\b",
     r"armas", re.IGNORECASE),
    (r"\barmor\b",
     r"armadura", re.IGNORECASE),
    (r"\barmour\b",
     r"armadura", re.IGNORECASE),
    (r"\bhelmet\b",
     r"casco", re.IGNORECASE),
    (r"\bglove\b",
     r"guante", re.IGNORECASE),
    (r"\bboot\b",
     r"bota", re.IGNORECASE),
    (r"\bcloak\b",
     r"capa", re.IGNORECASE),
    (r"\brobe\b",
     r"túnica", re.IGNORECASE),
    (r"\bpouch\b",
     r"bolsa", re.IGNORECASE),
    (r"\bpack\b",
     r"mochila", re.IGNORECASE),
    (r"\bbag\b",
     r"bolsa", re.IGNORECASE),
    (r"\bchest\b",
     r"cofre", re.IGNORECASE),
    (r"\bbox\b",
     r"caja", re.IGNORECASE),
    (r"\bjar\b",
     r"tarro", re.IGNORECASE),
    (r"\bbottle\b",
     r"botella", re.IGNORECASE),
    (r"\bflask\b",
     r"frasco", re.IGNORECASE),

    # =========================================================
    # FINAL CLEANUP / MISC PHRASES
    # =========================================================
    (r"\broll a d20\b",
     r"tira un d20", re.IGNORECASE),
    (r"\broll d20\b",
     r"tira d20", re.IGNORECASE),
    (r"\bthe d20\b",
     r"el d20", re.IGNORECASE),
    (r"\ba d20\b",
     r"un d20", re.IGNORECASE),
    (r"\bwith advantage\b",
     r"con ventaja", re.IGNORECASE),
    (r"\bwith disadvantage\b",
     r"con desventaja", re.IGNORECASE),
    (r"\bthe same turn\b",
     r"el mismo turno", re.IGNORECASE),
    (r"\bthe next turn\b",
     r"el siguiente turno", re.IGNORECASE),
    (r"\bthe previous turn\b",
     r"el turno anterior", re.IGNORECASE),
    (r"\ba turn\b",
     r"un turno", re.IGNORECASE),
    (r"\ba round\b",
     r"una ronda", re.IGNORECASE),
    (r"\bwhen triggered\b",
     r"cuando se activa", re.IGNORECASE),
    (r"\bwhen activated\b",
     r"cuando se activa", re.IGNORECASE),
    (r"\bwhen cast\b",
     r"cuando se lanza", re.IGNORECASE),
    (r"\bwhen dispelled\b",
     r"cuando se disipa", re.IGNORECASE),
    (r"\buntil dispelled\b",
     r"hasta que se disipe", re.IGNORECASE),
    (r"\bdispel magic\b",
     r"disipar magia", re.IGNORECASE),
    (r"\bcounterspell\b",
     r"contraconjuro", re.IGNORECASE),
    (r"\bdetect magic\b",
     r"detectar magia", re.IGNORECASE),
    (r"\bidentify\b",
     r"identificar", re.IGNORECASE),
    (r"\bsee invisibility\b",
     r"ver lo invisible", re.IGNORECASE),
    (r"\btrueseeing\b",
     r"visión verdadera", re.IGNORECASE),
    (r"\btruesight\b",
     r"visión verdadera", re.IGNORECASE),
]


def _ability_es(ability):
    """Map English ability name to Spanish."""
    mapping = {
        "strength": "Fuerza",
        "dexterity": "Destreza",
        "constitution": "Constitución",
        "intelligence": "Inteligencia",
        "wisdom": "Sabiduría",
        "charisma": "Carisma",
    }
    return mapping.get(ability.lower(), ability)


# Pre-compile all patterns
_COMPILED = []
for entry in PATTERNS:
    pat, repl, flags = entry
    _COMPILED.append((re.compile(pat, flags), repl))


def translate_text(text):
    """Apply all translation patterns to a string."""
    if not text:
        return text
    for compiled_pat, repl in _COMPILED:
        try:
            text = compiled_pat.sub(repl, text)
        except Exception:
            pass
    return text


def main():
    base_dir = "/Users/fsrezende/Documents/algorithm/dd-5e"
    en_path = os.path.join(base_dir, "data/open5e/spells.json")
    es_path = os.path.join(base_dir, "data/open5e/spells-es.json")

    print("Loading files...")
    with open(en_path, encoding="utf-8") as f:
        spells_en = json.load(f)
    with open(es_path, encoding="utf-8") as f:
        spells_es = json.load(f)

    # Build a slug → index map for the ES list
    es_map = {s["slug"]: i for i, s in enumerate(spells_es)}
    en_map = {s["slug"]: s for s in spells_en}

    fields_to_translate = ["desc", "higher_level", "material", "range"]

    srd_slugs = [s["slug"] for s in spells_en if s.get("document__slug") == "wotc-srd"]
    print(f"Found {len(srd_slugs)} SRD spells to translate.")

    translated_count = 0
    sample_output = []

    for slug in srd_slugs:
        en_spell = en_map[slug]
        if slug not in es_map:
            # Spell not in ES file at all — skip
            continue
        idx = es_map[slug]
        es_spell = spells_es[idx]

        changed = False
        for field in fields_to_translate:
            en_val = en_spell.get(field, "")
            if not en_val:
                continue
            translated = translate_text(en_val)
            if translated != es_spell.get(field, ""):
                es_spell[field] = translated
                changed = True

        if changed:
            translated_count += 1
            if len(sample_output) < 5:
                sample_output.append({
                    "slug": slug,
                    "name": es_spell.get("name", slug),
                    "desc_snippet": es_spell.get("desc", "")[:200],
                })

    print(f"\nTranslated/updated {translated_count} SRD spells.")

    print("Saving updated spells-es.json...")
    with open(es_path, "w", encoding="utf-8") as f:
        json.dump(spells_es, f, ensure_ascii=False, indent=2)
    print("Done.")

    print("\n--- Sample translations ---")
    for sample in sample_output:
        print(f"\n[{sample['name']}]")
        print(f"  desc (snippet): {sample['desc_snippet']}")


if __name__ == "__main__":
    main()
